# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-27 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_question_testcases'),
        ('contest', '0012_question_testcases'),
    ]

    operations = [
    ]
